### ISSUE TITLE
unhandledrejection考虑到跨域问题了吗？

### ISSUE THREAD

**Issue by LhrAlander** [clouDr-f2e/mitojs#13]
> As best as I can tell, the cause is that "unhandledrejection" event handlers are silently ignored if they originate from a different script origin. (For more info, see MDN on same-origin policy.) Chrome is very strict with file URLs' security origins in particular, but I've found that unknowingly breaking the same origin policy can happen for other reasons too (such as developing in webpack-dev-server with Chrome Dev Tools open). See this Chrome issue for discussion.

**Comment by cjinhuo** [comment]
没有，甚至js跨域报错的话，都取不到，只能是script error

**Comment by LhrAlander** [comment]
> 没有，甚至js跨域报错的话，都取不到，只能是script error

嗯，目前来看只能是依赖于使用这个框架的项目自己的打包出来的处理script的情况了，确实框架不适合做这个处理，虽然没用这个框架，应该还是挺厉害的，加油

**Comment by cjinhuo** [comment]
不过使用cdn的话，可以在script标签上加上crossorigin就可以捕捉到了。
