### ISSUE TITLE
example 的优化

### ISSUE THREAD

**Issue by hehehai** [clouDr-f2e/mitojs#14]
可以使用 [MSW](https://mswjs.io/docs/api/rest) 做服务接口的模拟，拥有请求状态及响应，MSW 使用了 service workers，作为请求代理，和真实服务响应并无差异。
![image](https://user-images.githubusercontent.com/12692552/103082927-378acc00-4616-11eb-8755-c9a67b110e9a.png)
![image](https://user-images.githubusercontent.com/12692552/103082940-3e194380-4616-11eb-9379-6b61570b1292.png)

MSW 是作为开发环境使用的数据拦截及模拟的依赖工具，这里使用在 example 中使用，作为服务模拟，但应在 example 标识，MSW 的作用

我看到当前的 demo 中使用了个人的服务，为了缓解压力，同样在demo中使用MSW也会增强 mito 的特性展示

**Comment by cjinhuo** [comment]
了解了，MSW相当于在跑开发环境前端的同时也起了一个service workers，然后手动抛出mock rest接口，方便前端代码调用。等我加完单测后会加入MSW的实践。

**Comment by hehehai** [comment]
@cjinhuo  是的，有需要，我可以做一些能力之内的贡献😁

**Comment by cjinhuo** [comment]
😃   👌
