### ISSUE TITLE
是否支持taro第三方框架

### ISSUE THREAD

**Issue by allen-wIki** [clouDr-f2e/mitojs#19]
**Describe the bug**

**Expected behavior**

**Information**
 - Mitojs Version [e.g. v1.0.0]
 - Environment: [e.g. Vue2.6、Vue3.0、React17.0]
 - Error info stack [e.g. MITO is not defined]

**Comment by cjinhuo** [comment]
taro里面包含Vue2.6、Vue3、react，所以正常来说是支持的，比如引入vue：[https://github.com/clouDr-f2e/mitojs/blob/master/docs/guide.md#vue](vue指南)，但是taro可以选择平台编译，目前mitojs只覆盖了微信小程序的监控api，还没有覆盖支付宝小程序、字节跳转小程序等等，所以还没有办法完全支持小程序框架，目前除了微信小程序，其他小程序平台只能捕捉到部分错误
