### ISSUE TITLE
silentXhr和enableTraceId同时为true时请求头中不会带有traceId

### ISSUE THREAD

**Issue by zxjdc4132** [clouDr-f2e/mitojs#24]
背景：当silentXhr和enableTraceId同时为true时请求头中不会带有traceId

SDK_VERSION："1.2.7"

当前配置：

MITO.init({
  dsn: '/log/mito/report',
  apikey: '1iavk9zi8a5er2cf',
  silentXhr: true,
  enableTraceId: true,
  traceIdFieldName: 'traceId',
  includeHttpUrlTraceIdRegExp: /mito/,
  backTrackerId(){
    return store.getters.userInfo.userId;
  }
})

**Comment by cjinhuo** [comment]
silentXhr是表示不再监听（拦截）页面的所有xhr请求，也就没有在发送请求的时候添加请求头了

**Comment by zxjdc4132** [comment]
那enableTraceId岂不是失去了意义

**Comment by cjinhuo** [comment]
> 那enableTraceId岂不是失去了意义

enableTraceId的前提是在silentXhr为false情况下触发的

**Comment by zxjdc4132** [comment]
很多情况下请求链路是由后台监控无须前端参与

**Comment by cjinhuo** [comment]
> 很多情况下请求链路是由后台监控无须前端参与

是的，服务端肯定是有监控的，但是服务端的请求链路前端第一时间没法看到的，还有个好处是前端可以拿到具体的页面行为链路，比如点了哪个按钮发了哪个请求
