### ISSUE TITLE
现在有页面性能监控的实践么？

### ISSUE THREAD

**Issue by somta** [clouDr-f2e/mitojs#27]
现在有页面性能监控的实践么？比如我想知道一个路由加载到底使用了多久？

**Comment by cjinhuo** [comment]
> 现在有页面性能监控的实践么？比如我想知道一个路由加载到底使用了多久？

我觉得你这个有点像埋点，比如进来a路由开始计时，离开时再上报

页面性能指的是页面资源加载瀑布流、白屏时间等等
