### ISSUE TITLE
点击行为应该如何开启上报？

### ISSUE THREAD

**Issue by wishlong** [clouDr-f2e/mitojs#8]
点击行为只是收集进 breadcrumb 但并未上报，这个要怎么开启吗？

**Comment by cjinhuo** [comment]
点击行为不会上报，除非是遇到报错信息才会上报

**Comment by xccjk** [comment]
@cjinhuo 哈喽，想问一下SDK设计是只准备支持收集错误信息对吗？像自定义事件，PV/UV之类，页面性能监控之类的功能是不会包含在SDK设计里么。

**Comment by cjinhuo** [comment]
> @cjinhuo 哈喽，想问一下SDK设计是只准备支持收集错误信息对吗？像自定义事件，PV/UV之类，页面性能监控之类的功能是不会包含在SDK设计里么。

你说的这个功能应该是埋点SDK应该做的事，比如用户点击了哪个按钮、哪个用户进了哪个页面的统计。mitojs一开始的定位是只上报错误，但是用户行为会被收集到用户行为栈中，遇到错误时一并上报。但是mitojs还是提供了简易的手动上报，[详情点击](https://github.com/clouDr-f2e/mitojs/blob/master/docs/guide.md#%E6%89%8B%E5%8A%A8%E4%B8%8A%E6%8A%A5)
